name: Build Wallet Standalone APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Wallet Code
      uses: actions/checkout@v4

    - name: Install System Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install App Dependencies
      run: yarn install

    - name: Set up Java Environment
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create Assets Target Directory
      run: mkdir -p android/app/src/main/assets

    - name: Compile JavaScript Asset Bundle Standalone
      run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

    - name: Compile Standalone Release Package
      run: |
        cd android
        chmod +x gradlew
        ./gradlew clean
        ./gradlew assembleRelease -x bundleReleaseJsAndAssets

    - name: Upload Finished Wallet Installer
      uses: actions/upload-artifact@v4
      with:
        name: OX-Wallet-Release
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk
